services:
  metatool-web:
    container_name: metatool-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL_BUILD_TIME=postgresql://metatool:m3t4t00l@host.docker.internal:8432/metatool
    env_file:
      - .env
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
    ports:
      - '12005:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - DATABASE_URL="postgresql://$DATABASE_USER:$DATABASE_PASSWORD@metatool-postgres:5432/$DATABASE_NAME"
    volumes:
      - .env:/app/.env
    command: node --inspect=0.0.0.0:9229 server.js
    depends_on:
      metatool-postgres:
        condition: service_healthy
      drizzle-migrate:
        condition: service_completed_successfully  
      

  metatool-postgres:
    container_name: metatool-postgres
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '8432:5432'
    volumes:
      - metatool-postgres:/var/lib/postgresql/data

  drizzle-migrate:
    image: metatool/drizzle-kit:latest
    container_name: drizzle-migrate
    extra_hosts:
      - host.docker.internal:host-gateway
      - host:host-gateway
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    command: pnpm drizzle-kit migrate
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@metatool-postgres:5432/$DATABASE_NAME"
      
    depends_on:
      metatool-postgres:
        condition: service_healthy

volumes:
  metatool-postgres:
    driver: local
