# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

dotenv:
  - .env
  - .env.local

tasks:

  db:
    env:
      DATABASE_URL: "postgresql://metatool:m3t4t00l@localhost:8432/metatool"
    cmds: 
      - docker compose down -v
      - docker compose up metatool-postgres -d --wait
      - pnpm db:migrate:auth
      - pnpm db:generate
      - pnpm db:migrate
      - node scripts/apply-fix-auth-tables.js
      - node scripts/apply-fix-jwt-session.js

  build:
    cmds:
      - pnpm i
      - task: db
      - docker compose build

  start:
    cmds: 
      - docker compose up -d
      - docker compose logs -f
